### ISSUE TITLE
Custom Searcher | Start page

### ISSUE THREAD

**Issue by DemwE** [Klubuntu/BrowserEx#2]
Add option to change start page.

**Comment by Klubuntu** [comment]
Good Day,
@NoNameUwU thanks for report your issue.
Your issue will be reported.
Wait for the changes to appear in a future version.
Track your issue in changelog.
Have Nice Day
Klubuntu

**Comment by Klubuntu** [comment]
Custom Searcher partially added in **Alpha 1.8.5**
https://github.com/Klubuntu/BrowserEx/releases/tag/Alpha2

**Comment by Klubuntu** [comment]
Custom searcher added completely in **Beta 1.9**
https://github.com/Klubuntu/BrowserEx/releases/tag/Beta1
